runtime: python
api_version: 1
env: flex
entrypoint: gunicorn -b :$PORT app:app

runtime_config:
  python_version: 3

resources:
 cpu: 2
 memory_gb: 2.3
 disk_size_gb: 40

readiness_check:
 app_start_timeout_sec: 600